import ollama
import pydantic
import json
from modelUtils import getAvailableModels, getModelContextSize

from langchain_core.documents import Document

# Epic Ollama moment - The docstring is actually included when the class is serialized to JSON, so it provides extra context for mr LLM
class Metadata(pydantic.BaseModel):
    ''' Pydantic model for the metadata to be generated by the Ollama API
    https://ollama.com/blog/structured-outputs 
    
    Args:
        title: str - Title of the paper
        summary: str - Summary of the paper
        # authors: list[str] - Authors of the paper
        datasets: list[str] - Datasets used in the paper to achieve results
        metrics: list[str] - Metrics used to evaluate results
        methods: list[str] - Methods used to achieve results
        applications: list[str] - Realworld applications of the paper and why it can be useful
        limitations: list[str] - Limitations of the paper that need to be addressed
        areasOfImprovement: list[str] - At least 3 specific areas of improvement that could lead to innovation and how it can be achieved'''
    title: str
    summary: str
    # authors: list[str]
    datasets: list[str]
    metrics: list[str]
    methods: list[str]
    applications: list[str]
    limitations: list[str]
    areasOfImprovement: list[str]

def generateMetadata(text: str, modelName: str) -> dict:
    ''' Generates metadata from the given text using the specified model and returns it as a dictionary (JSON)'''
    try:
        # Determine context size dynamically
        context_size = getModelContextSize(modelName)
        response = ollama.generate(
            model=modelName,
            format=Metadata.model_json_schema(),
            options={"num_ctx": context_size, "temperature": 0.1},
            system="You are a research assistant that has been tasked with generating structured metadata for a research paper. Retry if the output is incomplete or inaccurate or failed.",
            prompt=f"""
                PROMPT: Generate metadata for the following research paper in JSON format.
                Ensure that all string values, especially items within lists (like datasets, metrics, methods, applications, limitations, areasOfImprovement), are complete and correctly spelled words or phrases. Do not split words into individual characters or add unnecessary characters like underscores unless they are part of a standard term.
                Use exact extracts/sections/titles/names where possible, but format them correctly as proper strings.
                Validate the output for accuracy and completeness.

                CONTENT: {text}..."""
        )
        return json.loads(response.response)
    except Exception as e:
        raise Exception(f"Metadata generation failed: {str(e)}")

def generateEmbedding(text: str, modelName: str) -> list[list[float]]:
    ''' Generates a vector embedding for the given text using the specified model '''
    try:
        response = ollama.embed(model=modelName, input=text)
        return response.embeddings
    except Exception as e:
        raise Exception(f"Embedding generation failed: {str(e)}")
    
def generateEmbedding(docs: list[Document], metadata: list[dict], model: str) -> list[list[float]]:
    ''' Generates embeddings for the given documents using the specified model '''
    try:
        response = ollama.embed(model=model, input=[doc.page_content for doc in docs])
        return response.embeddings
    except Exception as e:
        raise Exception(f"Embedding generation failed: {str(e)}")

if __name__ == "__main__": # Test the functions
    import arxiv
    import extractText

    print("Available Models: ", getAvailableModels(), "\n") # Find all available models

    client = arxiv.Client() # Create client
    search = arxiv.Search(id_list=["2310.11453"], max_results=1) # Search for the BitNet paper to test
    paper = client.results(search).__next__() # Get the paper

    path = paper.download_pdf("data/papers") # Download the paper
    text = extractText.extractText(path) # Extract text from the paper
    documents = extractText.chunkDocument(path) # Chunk the document into smaller parts

    # print(text)
    print(generateMetadata(text, "deepseek-r1:7b"))
    # print(generateEmbedding(text, "nomic-embed-text:latest"))